### ISSUE TITLE
Step interpolation example

### ISSUE THREAD

**Issue by maeishoj** [BorisChumichev/everpolate#1]
Hello there.

Could you provide logical example how step interpolation works?

Suppose I have a timeserie which has as x values = [ 5,6,7,10] and as y values = [ 50, 49, 48, 45 ] .
How can i use the step function to "fill in the gaps" and return the resulting array so I know what value y is at value x = 8 and x = 9?

**Comment by BorisChumichev** [comment]
You can do it like that:

``` javascript
const
  step = require('everpolate').step,
  X = [ 5, 6, 7, 10 ],
  Y = [ 50, 49, 48, 45 ];

console.log(step([8, 9], X, Y)); // [ 48, 48 ]
```
